---
- import_tasks: tasks/install_and_enable.yml
  vars:
    packages:
      - name: firewalld
    services:
      - name: firewalld
        enabled: true
        state: started

- name: Open the port for http
  ansible.posix.firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled
