---
- name: Install packages
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: latest
  loop: "{{ packages }}"

- name: Enable and start services
  ansible.builtin.service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  loop: "{{ services }}"
