---
  - name: Install firewall
    ansible.builtin.dnf:
      name: "{{ package }}"
      state: latest
  - name: Enable and start the firewall
    ansible.builtin.service:
      name: "{{ service }}"
      enabled: true
      state: started
  - name: Open the port for {{ rule }}
    ansible.posix.firewalld:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
    loop: "{{ rule }}"