---
- import_tasks: tasks/install_and_enable.yml
  vars:
    packages:
      - name: httpd
    services:
      - name: httpd
        enabled: true
        state: started

- name: Tuning configuration installed
  ansible.builtin.copy:
    src: files/tune.conf
    dest: /etc/httpd/conf.d/tune.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
