---
- name: Enable internet services
  hosts: serverb.lab.example.com
  become: true
  tasks:
    - name: Install Latest versions of requeriments packages
      ansible.builtin.dnf:
        name:
          - httpd
          - firewalld
          - mariadb-server
          - php
          - php-mysqlnd
        state: latest
    - name: Enable and start firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: Allow http service in firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
    - name: Enable and start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Enable and start mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Copy index.php to web server
      ansible.builtin.copy:
        src: /home/student/playbook-review/index.php
        dest: /var/www/html
        mode: 0644
- name: Test web server access from control node
  hosts: workstation.lab.example.com
  tasks:
    - name: Test web service on serverb
      ansible.builtin.uri:
        url: http://serverb.lab.example.com
        return_content: no
        status_code: 200