version: '3.7'
services:
  quotes-provider:
    image: registry.ocp4.example.com:8443/redhattraining/wiremock
    container_name: 'quotes-provider'
    volumes:
      - ./wiremock/stubs:/home/wiremock:Z
    environment:
      - QUOTES_SERVICE=http://quotes-provider:8080
    networks:
      - lab-net

  quotes-api:
    image: registry.ocp4.example.com:8443/redhattraining/podman-quotesapi-compose
    container_name: 'quotes-api'
    ports:
      - '8080:8080'
    environment:
      - QUOTES_SERVICE=http://quotes-provider:8080
    networks:
      - lab-net

  quotes-ui:
    image: registry.ocp4.example.com:8443/redhattraining/podman-quotes-ui
    container_name: 'quotes-ui'
    ports:
      - '3000:8080'

networks:
  lab-net:
    driver: bridge
